import { Tour } from './types';

export const getLocalTours = async (): Promise<Tour[]> => {
  return [
    {
      id: 't1',
      name: 'El Nido Tour A: Lagoons and Beaches',
      location: 'El Nido',
      description: 'Explore the famous Big Lagoon, Secret Lagoon, and Shimizu Island. Perfect for kayaking and snorkeling.',
      price: 1200,
      originalPrice: 1500,
      image: '/images/tours/tourA_BigLagoon.png',
      images: ['/images/tours/tourA_BigLagoon.png', '/images/tours/tourA_SecretLagoon.png'],
      highlights: ['Big Lagoon', 'Secret Lagoon', 'Shimizu Island'],
      activities: ['Kayaking', 'Snorkeling'],
      isBestSeller: true,
    },
    {
      id: 't2',
      name: 'El Nido Tour B: Caves and Coves',
      location: 'El Nido',
      description: 'Discover hidden caves and beautiful coves including Snake Island and Cudugnon Cave.',
      price: 1200,
      originalPrice: 1600,
      image: '/images/tours/tourB_CathedralCave.jpg',
      images: ['/images/tours/tourB_CathedralCave.jpg', '/images/tours/tourB_SnakeIsland.jpg'],
      highlights: ['Entalula Island', 'Codugnon Cave', 'Snake Island'],
      activities: ['Boat Ride', 'Snorkeling'],
      isBestSeller: false,
    },
    {
      id: 't3',
      name: 'El Nido Tour C: Hidden Beaches and Shrines',
      location: 'El Nido',
      description: 'Visit the most beautiful beaches in El Nido including Hidden Beach and Matinloc Shrine.',
      price: 1300,
      originalPrice: 1800,
      image: '/images/tours/tourC_HelicopterIsland.webp',
      images: ['/images/tours/tourC_HelicopterIsland.webp'],
      highlights: ['Secret Beach', 'Matinloc Shrine', 'Helicopter Island'],
      activities: ['Sightseeing', 'Beach Hopping'],
      isBestSeller: true,
    },
    {
      id: 't4',
      name: 'El Nido Tour D: Cadlao Lagoons',
      location: 'El Nido',
      description: 'A more relaxed tour focusing on the beautiful lagoons of Cadlao Island.',
      price: 1100,
      originalPrice: 1500,
      image: '/images/tours/tourD_CadlaoLagoon.jpg',
      images: ['/images/tours/tourD_CadlaoLagoon.jpg'],
      highlights: ['Cadlao Lagoon', 'Paradise Beach', 'Ipil Beach'],
      activities: ['Snorkeling', 'Island Hopping'],
      isBestSeller: true,
    },
    {
      id: 't5',
      name: 'Underground River Tour w/ buffet lunch',
      location: 'Puerto Princesa',
      description: 'Explore one of the New 7 Wonders of Nature in Puerto Princesa.',
      price: 2150,
      originalPrice: 2700,
      image: '/images/tours/ppc_undergroundriver.jpg',
      images: ['/images/tours/ppc_undergroundriver.jpg'],
      highlights: ['Underground River', 'Ugong', 'Lunch Buffet'],
      activities: ['Boat Tour', 'Cave Visit'],
      isBestSeller: true,
    },
    {
      id: 't6',
      name: 'Puerto Princesa City Tour',
      location: 'Puerto Princesa',
      description: 'Running Tour at Baywalk, Plaza Cuartel, Cathedral, Mitras Ranch, Bakers Hill, Butterfly Garden/Crocodile Farm, and Pasalubong Centers.',
      price: 750,
      originalPrice: 1000,
      image: '/images/tours/city_crocodilefarm.jpg',
      images: ['/images/tours/city_crocodilefarm.jpg'],
      highlights: ['Crocodile Farm', 'Bakers Hill', 'Plaza Cuartel'],
      activities: ['City Tour', 'Local Sightseeing'],
      isBestSeller: true,
    },
    {
      id: 't7',
      name: 'Honda Bay Island Hopping w/ lunch',
      location: 'Puerto Princesa',
      description: 'Pambato reef, Luli Island/Starfish Island and Cowrie Island.',
      price: 1750,
      originalPrice: 2000,
      image: '/images/tours/hb_Island1.jpg',
      images: ['/images/tours/hb_Island1.jpg'],
      highlights: ['Honda Bay', 'Starfish Island', 'Cowrie Island'],
      activities: ['Island Hopping', 'Snorkeling'],
      isBestSeller: true,
    },
    {
      id: 't8',
      name: 'Firefly Watching w/ dinner',
      location: 'Puerto Princesa',
      description: 'A night filled with firefly magic.',
      price: 1600,
      originalPrice: 2000,
      image: '/images/tours/ff_1.jpg',
      images: ['/images/tours/ff_1.jpg'],
      highlights: ['Firefly Watching', 'Night Boat Ride'],
      activities: ['Evening Cruise'],
      isBestSeller: true,
    },
    {
      id: 't9',
      name: 'Port Barton Promo Tours',
      location: 'Port Barton',
      description: 'Port Barton: Where time slows and paradise begins.',
      price: 1500,
      originalPrice: 1900,
      image: '/images/tours/br_TurtleSpot.jpg',
      images: ['/images/tours/br_TurtleSpot.jpg'],
      highlights: ['Turtle Spot', 'Sand Bar', 'Twin Reef'],
      activities: ['Beach Relaxation', 'Snorkeling'],
      isBestSeller: true,
    },
    {
      id: 't91',
      name: 'San Vicente Land Tour',
      location: 'Port Barton',
      description: 'Your Gateway to Hidden Paradise.',
      price: 1800,
      originalPrice: 2100,
      image: '/images/tours/br_landtour.jpg',
      images: ['/images/tours/br_landtour.jpg'],
      highlights: ['Long Beach', 'Bato ni Ningning', 'San Vic View Point'],
      activities: ['Land Tour', 'Hiking'],
      isBestSeller: true,
    },
    {
      id: 't10',
      name: 'Coron Tour A',
      location: 'Coron',
      description: 'Where Every Island Feels Like Paradise.',
      price: 1100,
      originalPrice: 1500,
      image: '/images/tours/cr_TourA.jpg',
      images: ['/images/tours/cr_TourA.jpg'],
      highlights: ['Kayangan Lake', 'Quin Reef', 'Atwayan Beach'],
      activities: ['Island Hopping', 'Swimming'],
      isBestSeller: true,
    },
    {
      id: 't11',
      name: 'Coron Tour B',
      location: 'Coron',
      description: 'Where Every Island Feels Like Paradise.',
      price: 1400,
      originalPrice: 1900,
      image: '/images/tours/cr_TourB.jpg',
      images: ['/images/tours/cr_TourB.jpg'],
      highlights: ['Barracuda Lake', 'Twin Lagoon', 'Reef Garden'],
      activities: ['Snorkeling', 'Scenic Views'],
      isBestSeller: true,
    },
    {
      id: 't12',
      name: 'Coron Tour C',
      location: 'Coron',
      description: 'Where Every Island Feels Like Paradise.',
      price: 1800,
      originalPrice: 2100,
      image: '/images/tours/cr_TourC.jpg',
      images: ['/images/tours/cr_TourC.jpg'],
      highlights: ['Malcapuya Island', 'Ditaytayan Island', 'Coco Beach'],
      activities: ['Island Hopping', 'Beach Time'],
      isBestSeller: true,
    },
    {
      id: 't13',
      name: 'Safari',
      location: 'Coron',
      description: 'Where Adventure Meets the Wild.',
      price: 1800,
      originalPrice: 2100,
      image: '/images/tours/cr_Safari.jpg',
      images: ['/images/tours/cr_Safari.jpg'],
      highlights: ['Malcapuya Island', 'Ditaytayan Island', 'Coco Beach'],
      activities: ['Island Adventure', 'Wildlife Viewing'],
      isBestSeller: true,
    },
    {
      id: 't14',
      name: 'Coron Town Tour',
      location: 'Coron',
      description: 'A Deeper Look at Coron\'s Local Charm.',
      price: 900,
      originalPrice: 1250,
      image: '/images/tours/cr_TownTour.jpg',
      images: ['/images/tours/cr_TownTour.jpg'],
      highlights: ['Souvenir Shop', 'Lualhati Park', 'Mt. Tapyas'],
      activities: ['Local Sightseeing', 'Cultural Tour'],
      isBestSeller: true,
    },
  ];
};

export default getLocalTours;
